// <auto-generated />
using System;
using ApiDePapas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiDePapas.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApiDePapas.Domain.Entities.Address", b =>
                {
                    b.Property<int>("address_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("address_id"));

                    b.Property<string>("locality_name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "locality_name");

                    b.Property<int>("number")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "number");

                    b.Property<string>("postal_code")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "postal_code");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "street");

                    b.HasKey("address_id");

                    b.HasIndex("postal_code", "locality_name")
                        .HasDatabaseName("IX_Addresses_locality_fk");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ApiDePapas.Domain.Entities.DistributionCenter", b =>
                {
                    b.Property<int>("distribution_center_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("distribution_center_id"));

                    b.Property<int>("address_id")
                        .HasColumnType("int");

                    b.HasKey("distribution_center_id");

                    b.HasIndex("address_id")
                        .HasDatabaseName("IX_DistributionCenters_address_id");

                    b.ToTable("DistributionCenters");
                });

            modelBuilder.Entity("ApiDePapas.Domain.Entities.Locality", b =>
                {
                    b.Property<string>("postal_code")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("locality_name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("lat")
                        .HasColumnType("float");

                    b.Property<float>("lon")
                        .HasColumnType("float");

                    b.Property<string>("state_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("postal_code", "locality_name");

                    b.HasIndex("locality_name")
                        .HasDatabaseName("IX_Localities_locality_name");

                    b.ToTable("Localities");
                });

            modelBuilder.Entity("ApiDePapas.Domain.Entities.ShippingDetail", b =>
                {
                    b.Property<int>("shipping_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("shipping_id"));

                    b.Property<string>("carrier_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("delivery_address_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("estimated_delivery_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("order_id")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<float>("total_cost")
                        .HasColumnType("float");

                    b.Property<string>("tracking_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("travel_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("shipping_id");

                    b.HasIndex("created_at")
                        .HasDatabaseName("IX_Shippings_created_at");

                    b.HasIndex("delivery_address_id")
                        .HasDatabaseName("IX_Shippings_delivery_address_id");

                    b.HasIndex("status")
                        .HasDatabaseName("IX_Shippings_status");

                    b.HasIndex("travel_id")
                        .HasDatabaseName("IX_Shippings_travel_id");

                    b.ToTable("Shippings");
                });

            modelBuilder.Entity("ApiDePapas.Domain.Entities.TransportMethod", b =>
                {
                    b.Property<int>("transport_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("transport_id"));

                    b.Property<string>("available")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("average_speed")
                        .HasColumnType("float");

                    b.Property<float>("max_capacity")
                        .HasColumnType("float");

                    b.Property<string>("transport_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("transport_id");

                    b.ToTable("TransportMethods");
                });

            modelBuilder.Entity("ApiDePapas.Domain.Entities.Travel", b =>
                {
                    b.Property<int>("travel_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("travel_id"));

                    b.Property<DateTime?>("arrival_time")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("departure_time")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("distribution_center_id")
                        .HasColumnType("int");

                    b.Property<int>("transport_method_id")
                        .HasColumnType("int");

                    b.HasKey("travel_id");

                    b.HasIndex("distribution_center_id")
                        .HasDatabaseName("IX_Travels_distribution_center_id");

                    b.HasIndex("transport_method_id")
                        .HasDatabaseName("IX_Travels_transport_method_id");

                    b.ToTable("Travels");
                });

            modelBuilder.Entity("ApiDePapas.Domain.Entities.Address", b =>
                {
                    b.HasOne("ApiDePapas.Domain.Entities.Locality", "Locality")
                        .WithMany()
                        .HasForeignKey("postal_code", "locality_name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locality");
                });

            modelBuilder.Entity("ApiDePapas.Domain.Entities.DistributionCenter", b =>
                {
                    b.HasOne("ApiDePapas.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("address_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("ApiDePapas.Domain.Entities.ShippingDetail", b =>
                {
                    b.HasOne("ApiDePapas.Domain.Entities.Address", "DeliveryAddress")
                        .WithMany("DeliveredShippings")
                        .HasForeignKey("delivery_address_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiDePapas.Domain.Entities.Travel", "Travel")
                        .WithMany("Shippings")
                        .HasForeignKey("travel_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ApiDePapas.Domain.Entities.ProductQty", "products", b1 =>
                        {
                            b1.Property<int>("RowId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("RowId"));

                            b1.Property<int>("ShippingDetailshipping_id")
                                .HasColumnType("int");

                            b1.Property<int>("id")
                                .HasColumnType("int")
                                .HasAnnotation("Relational:JsonPropertyName", "product_id");

                            b1.Property<int>("quantity")
                                .HasColumnType("int")
                                .HasAnnotation("Relational:JsonPropertyName", "quantity");

                            b1.HasKey("RowId", "ShippingDetailshipping_id");

                            b1.HasIndex("ShippingDetailshipping_id")
                                .HasDatabaseName("IX_ProductQty_ShippingDetailshipping_id");

                            b1.ToTable("ProductQty", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ShippingDetailshipping_id");
                        });

                    b.OwnsMany("ApiDePapas.Domain.Entities.ShippingLog", "logs", b1 =>
                        {
                            b1.Property<int>("ShippingDetailshipping_id")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasAnnotation("Relational:JsonPropertyName", "message");

                            b1.Property<int?>("Status")
                                .HasColumnType("int")
                                .HasAnnotation("Relational:JsonPropertyName", "status");

                            b1.Property<DateTime?>("Timestamp")
                                .HasColumnType("datetime(6)")
                                .HasAnnotation("Relational:JsonPropertyName", "timestamp");

                            b1.HasKey("ShippingDetailshipping_id", "Id");

                            b1.HasIndex("ShippingDetailshipping_id")
                                .HasDatabaseName("IX_ShippingLog_ShippingDetailshipping_id");

                            b1.ToTable("ShippingLog", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ShippingDetailshipping_id");
                        });

                    b.Navigation("DeliveryAddress");

                    b.Navigation("Travel");

                    b.Navigation("logs");

                    b.Navigation("products");
                });

            modelBuilder.Entity("ApiDePapas.Domain.Entities.Travel", b =>
                {
                    b.HasOne("ApiDePapas.Domain.Entities.DistributionCenter", "DistributionCenter")
                        .WithMany()
                        .HasForeignKey("distribution_center_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiDePapas.Domain.Entities.TransportMethod", "TransportMethod")
                        .WithMany()
                        .HasForeignKey("transport_method_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistributionCenter");

                    b.Navigation("TransportMethod");
                });

            modelBuilder.Entity("ApiDePapas.Domain.Entities.Address", b =>
                {
                    b.Navigation("DeliveredShippings");
                });

            modelBuilder.Entity("ApiDePapas.Domain.Entities.Travel", b =>
                {
                    b.Navigation("Shippings");
                });
#pragma warning restore 612, 618
        }
    }
}
