"""
Django settings for Main project.

Generated by 'django-admin startproject' using Django 5.1.1.
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv
# --- BASE_DIR (unificado, no lo redefinas más abajo) ---
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")
AUTH_USER_MODEL = 'administracion.Usuario'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8io^32_+@-bwm(q8@jdflu^^6-_btdevo5p%1uc%l*od_70i=2'
# TIP: en producción, usá variables de entorno.

# la url utilizada
SITE_URL = os.getenv("SITE_URL", "http://127.0.0.1:8000").rstrip("/")
SITE_URL = os.getenv("SITE_URL", "http://127.0.0.1:8000").rstrip("/")
BASE_URL = os.getenv("BASE_URL", "http://127.0.0.1:8000").rstrip("/")
# SITE_URL = "https://tcc25.myqnapcloud.com"
# BASE_URL = "https://tcc25.myqnapcloud.com"

def _normalize_prefix(value: str | None) -> str:
    if not value:
        return ""
    prefix = value.strip()
    if not prefix:
        return ""
    if not prefix.startswith("/"):
        prefix = "/" + prefix
    if prefix != "/":
        prefix = prefix.rstrip("/")
    return prefix

APP_PATH_PREFIX = _normalize_prefix(os.getenv("APP_PATH_PREFIX", "/compras"))
FORCE_SCRIPT_NAME = APP_PATH_PREFIX or None

def build_prefixed_path(path: str = "/") -> str:
    """Construct a path that includes the configured application prefix."""
    segment = path or "/"
    if not segment.startswith("/"):
        segment = "/" + segment
    if not APP_PATH_PREFIX:
        return segment
    normalized_prefix = APP_PATH_PREFIX.rstrip("/")
    suffix = segment.lstrip("/")
    if not suffix:
        return f"{normalized_prefix}/"
    return f"{normalized_prefix}/{suffix}"

def build_public_url(path: str = "/") -> str:
    base = SITE_URL.rstrip("/")
    return f"{base}{build_prefixed_path(path)}"

DEBUG = os.getenv("DEBUG", "true").lower() == "true"
ALLOWED_HOSTS = ['*']

_extra_csrf_origins = [
    origin.strip()
    for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]
CSRF_TRUSTED_ORIGINS = sorted(
    {
        SITE_URL,
        "http://127.0.0.1",
        "http://localhost",
        *_extra_csrf_origins,
    }
)

# ==========================================
# CONFIGURACIÓN DE APIS MOCK/EXTERNAS
# ==========================================
# Cambiar USE_MOCK_APIS a False en producción para usar APIs reales
USE_MOCK_APIS = os.getenv("USE_MOCK_APIS", "true").lower() == "true"

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS
# ==========================================
# Switch para elegir entre SQLite (desarrollo local) y PostgreSQL (producción/Docker)
USE_SQLITE = os.getenv("USE_SQLITE", "true").lower() == "true"

base_url_api = os.getenv("BASE_API_URL", build_public_url("/api/"))
STOCK_API_BASE_URL = os.getenv("STOCK_API_BASE_URL", "http://localhost:8000")
LOGISTICA_API_BASE_URL = os.getenv("LOGISTICA_API_BASE_URL", "http://localhost:8000")
PRODUCTOS_API_BASE_URL = os.getenv(
    "PRODUCTOS_API_BASE_URL",
    build_public_url("/").rstrip("/"),
)

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Requerido por allauth

    # Apps del proyecto
    'apps.modulos.inicio',
    'apps.modulos.administracion',
    'apps.modulos.login',
    'apps.modulos.pedidos',

    # APIs internas
    'apps.apis.carritoApi',
    'apps.apis.productoApi',
    'apps.apis.pedidoApi',
    
    # Django REST Framework
    'rest_framework',
    'drf_spectacular',  # Swagger/OpenAPI
    
    # Aplicaciones allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid_connect',


    # Opcionalmente crispy-forms
    'crispy_forms',
]

SITE_ID = 1



AUTHENTICATION_BACKENDS = [
    # 'apps.login.backends.EmailBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # <-- primero esto
    'Main.middleware_request_id.RequestContextMiddleware',      # <-- y recién después el nuestro
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]


ROOT_URLCONF = 'Main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Main.wsgi.application'

# Database
# Configuración dinámica: SQLite para desarrollo local, PostgreSQL para Docker
if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'compras_db'),
            'USER': os.getenv('POSTGRES_USER', 'compras_user'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'compras_password'),
            'HOST': os.getenv('POSTGRES_HOST', 'postgres'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }

SECURE_SSL_REDIRECT = False

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True

# Static & Media (usando BASE_DIR Path)
STATIC_URL = build_prefixed_path("/static/")
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = build_prefixed_path("/media/")
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# ====================================
# Configuración de Django REST Framework
# ====================================
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.modulos.login.authentication.KeycloakJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

USE_X_FORWARDED_PREFIX = True
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

CSRF_TRUSTED_ORIGINS = sorted(
    set(CSRF_TRUSTED_ORIGINS)
    | {
        'https://tcc25.myqnapcloud.com',
        'http://0.0.0.0:8000',
    }
)


# Configuracion de correo (TIP: mover a variables de entorno en prod)
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

SOCIALACCOUNT_ADAPTER = "apps.modulos.login.adapters.MySocialAccountAdapter"

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'max.prueba.200@gmail.com'  # Tu dirección de correo electrónico personal
EMAIL_HOST_PASSWORD = 'dbcasxwvzgedgicp'  # La contraseña de tu cuenta de correo electrónico


# ====================================
# Configuración de DRF Spectacular (Swagger/OpenAPI)
# ====================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'DesarrolloAPP - API Mock Documentation',
    'DESCRIPTION': 'Documentación completa de las APIs Mock de Stock y Logística para desarrollo y testing',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api',
    
    # Configuración de UI
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
        'defaultModelsExpandDepth': 2,
        'defaultModelExpandDepth': 2,
        'displayRequestDuration': True,
    },
    
    # Ordenamiento de endpoints
    'SORT_OPERATIONS': True,
    
    # Tags para organizar endpoints
    'TAGS': [
        {'name': 'Stock Mock', 'description': 'Operaciones de gestión de stock y productos'},
        {'name': 'Logística Mock', 'description': 'Operaciones de envíos y transporte'},
        {'name': 'Productos', 'description': 'API de productos (consume Stock)'},
    ],
}

# Ya configurado anteriormente para usar apps.modulos.login.adapters.MySocialAccountAdapter

# Logging: enviar únicamente a consola (stdout) durante desarrollo
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "%(asctime)s %(levelname)s %(name)s %(message)s"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "stream": "ext://sys.stdout",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "apps.modulos.inicio": {"handlers": ["console"], "level": "DEBUG", "propagate": False},
        "apps.apis.stockApi": {"handlers": ["console"], "level": "DEBUG", "propagate": False},
    },
}


# =============================
# Configuración de Keycloak OIDC
# =============================
KEYCLOAK_BASE_URL = os.getenv("KEYCLOAK_BASE_URL", "http://localhost:8080")
KEYCLOAK_PUBLIC_BASE_URL = os.getenv("KEYCLOAK_PUBLIC_BASE_URL", KEYCLOAK_BASE_URL)
KEYCLOAK_REALM = os.getenv("KEYCLOAK_REALM", "ds-2025-realm")
KEYCLOAK_CLIENT_ID = os.getenv("KEYCLOAK_CLIENT_ID", "grupo-04")
KEYCLOAK_CLIENT_SECRET = os.getenv("KEYCLOAK_CLIENT_SECRET", "")
KEYCLOAK_USE_PKCE = os.getenv("KEYCLOAK_USE_PKCE", "true").lower() == "true"
KEYCLOAK_SCOPE = os.getenv(
    "KEYCLOAK_SCOPE",
    "openid",
).split()
KEYCLOAK_SERVER_URL = os.getenv(
    "KEYCLOAK_SERVER_URL",
    f"{KEYCLOAK_BASE_URL.rstrip('/')}/realms/{KEYCLOAK_REALM}",
)
KEYCLOAK_PUBLIC_SERVER_URL = os.getenv(
    "KEYCLOAK_PUBLIC_SERVER_URL",
    f"{KEYCLOAK_PUBLIC_BASE_URL.rstrip('/')}/realms/{KEYCLOAK_REALM}",
)
KEYCLOAK_ISSUER_URL = os.getenv("KEYCLOAK_ISSUER_URL", KEYCLOAK_PUBLIC_SERVER_URL)
KEYCLOAK_JWKS_URL = os.getenv(
    "KEYCLOAK_JWKS_URL",
    f"{KEYCLOAK_SERVER_URL.rstrip('/')}/protocol/openid-connect/certs",
)
KEYCLOAK_TOKEN_URL = os.getenv(
    "KEYCLOAK_TOKEN_URL",
    f"{KEYCLOAK_SERVER_URL.rstrip('/')}/protocol/openid-connect/token",
)
_keycloak_expected_aud_raw = os.getenv("KEYCLOAK_EXPECTED_AUDIENCE", KEYCLOAK_CLIENT_ID).strip()
if _keycloak_expected_aud_raw:
    _aud_parts = [part.strip() for part in _keycloak_expected_aud_raw.split(",") if part.strip()]
    KEYCLOAK_EXPECTED_AUDIENCE = _aud_parts[0] if len(_aud_parts) == 1 else _aud_parts
else:
    KEYCLOAK_EXPECTED_AUDIENCE = None
KEYCLOAK_SERVICE_CLIENT_ID = os.getenv(
    "KEYCLOAK_SERVICE_CLIENT_ID",
    KEYCLOAK_CLIENT_ID,
)
KEYCLOAK_SERVICE_CLIENT_SECRET = os.getenv(
    "KEYCLOAK_SERVICE_CLIENT_SECRET",
    KEYCLOAK_CLIENT_SECRET,
)
KEYCLOAK_SERVICE_SCOPE = os.getenv(
    "KEYCLOAK_SERVICE_SCOPE",
    "openid profile email",
)

DEFAULT_KEYCLOAK_REDIRECT_PATH = "/accounts/oidc/keycloak/login/callback/"
KEYCLOAK_LOGIN_REDIRECT_URI = os.getenv(
    "KEYCLOAK_LOGIN_REDIRECT_URI",
    build_public_url(DEFAULT_KEYCLOAK_REDIRECT_PATH),
)
KEYCLOAK_LOGOUT_REDIRECT_URI = os.getenv(
    "KEYCLOAK_LOGOUT_REDIRECT_URI",
    "",
).strip() or None
_keycloak_settings = {
    'server_url': KEYCLOAK_PUBLIC_SERVER_URL,
    'use_pkce': KEYCLOAK_USE_PKCE,
    'auth_params': {
        'scope': ' '.join(KEYCLOAK_SCOPE),
    },
}
if KEYCLOAK_CLIENT_SECRET:
    _keycloak_settings['token_auth_method'] = 'client_secret_post'
else:
    _keycloak_settings['token_auth_method'] = 'none'

SOCIALACCOUNT_PROVIDERS = {
    'openid_connect': {
        'APPS': [
            {
                'provider_id': 'keycloak',
                'name': 'Keycloak',
                'client_id': KEYCLOAK_CLIENT_ID,
                'secret': KEYCLOAK_CLIENT_SECRET or None,
                'settings': _keycloak_settings,
            }
        ],
    }
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = KEYCLOAK_LOGOUT_REDIRECT_URI or '/'
