# Generated by Django 5.2.6 on 2025-10-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
