# Generated by Django 5.2.6 on 2025-10-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='user',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
