
MOCK_PRODUCTS = [
    # --- ROPA: REMERAS ---
    {
        "id": 1,
        "nombre": "Remera básica blanca",
        "descripcion": "Remera de algodón 100% peinado, corte clásico.",
        "precio": 5999.99,
        "stock": 40,
        "categoria": "Remeras",
        "marca": "UrbanFit",
        "imagen_url": "/static/imagenes/mock/remera_basica_blanca.webp",
    },
    {
        "id": 2,
        "nombre": "Remera negra oversize",
        "descripcion": "Remera oversize unisex, tejido pesado.",
        "precio": 6999.99,
        "stock": 30,
        "categoria": "Remeras",
        "marca": "UrbanFit",
        "imagen_url": "/static/imagenes/mock/remera_oversize_negra.webp",
    },
    {
        "id": 3,
        "nombre": "Remera estampada vintage",
        "descripcion": "Remera con estampa retro, algodón liviano.",
        "precio": 6499.00,
        "stock": 25,
        "categoria": "Remeras",
        "marca": "UrbanFit",
        "imagen_url": "/static/imagenes/mock/remera_estampada_vintage.webp",
    },
    {
        "id": 4,
        "nombre": "Remera deportiva dry-fit",
        "descripcion": "Remera técnica respirable para entrenamiento.",
        "precio": 7999.00,
        "stock": 35,
        "categoria": "Remeras",
        "marca": "ProSport",
        "imagen_url": "/static/imagenes/mock/remera_dryfit.webp",
    },
    {
        "id": 5,
        "nombre": "Remera manga larga",
        "descripcion": "Remera manga larga ideal para entretiempo.",
        "precio": 7499.00,
        "stock": 20,
        "categoria": "Remeras",
        "marca": "ClassicLine",
        "imagen_url": "/static/imagenes/mock/remera_manga_larga.webp",
    },

    # --- PANTALONES ---
    {
        "id": 6,
        "nombre": "Jean slim azul oscuro",
        "descripcion": "Pantalón de jean slim fit con algo de elastano.",
        "precio": 14999.00,
        "stock": 28,
        "categoria": "Pantalones",
        "marca": "DenimCo",
        "imagen_url": "/static/imagenes/mock/jean_slim_azul.webp",
    },
    {
        "id": 7,
        "nombre": "Jean mom celeste",
        "descripcion": "Jean tiro alto mom fit, lavado claro.",
        "precio": 15999.00,
        "stock": 22,
        "categoria": "Pantalones",
        "marca": "DenimCo",
        "imagen_url": "/static/imagenes/mock/jean_mom_celeste.webp",
    },
    {
        "id": 8,
        "nombre": "Jogger frisa negro",
        "descripcion": "Jogger de frisa con puños elastizados.",
        "precio": 11999.00,
        "stock": 35,
        "categoria": "Pantalones",
        "marca": "ProSport",
        "imagen_url": "/static/imagenes/mock/jogger_frisa_negro.webp",
    },
    {
        "id": 9,
        "nombre": "Pantalón chino beige",
        "descripcion": "Pantalón chino entallado, gabardina suave.",
        "precio": 13999.00,
        "stock": 18,
        "categoria": "Pantalones",
        "marca": "ClassicLine",
        "imagen_url": "/static/imagenes/mock/chino_beige.webp",
    },
    {
        "id": 10,
        "nombre": "Short deportivo running",
        "descripcion": "Short liviano con calza interna para correr.",
        "precio": 9999.00,
        "stock": 40,
        "categoria": "Pantalones",
        "marca": "ProSport",
        "imagen_url": "/static/imagenes/mock/short_running.webp",
    },

    # --- ZAPATILLAS ---
    {
        "id": 11,
        "nombre": "Zapatillas urbanas blancas",
        "descripcion": "Zapatillas urbanas de cuero sintético.",
        "precio": 25999.00,
        "stock": 15,
        "categoria": "Zapatillas",
        "marca": "StepUp",
        "imagen_url": "/static/imagenes/mock/zapatillas_urbanas_blancas.webp",
    },
    {
        "id": 12,
        "nombre": "Zapatillas running pro",
        "descripcion": "Zapatillas para running con amortiguación extra.",
        "precio": 29999.00,
        "stock": 20,
        "categoria": "Zapatillas",
        "marca": "ProSport",
        "imagen_url": "/static/imagenes/mock/zapatillas_running_pro.webp",
    },
    {
        "id": 13,
        "nombre": "Zapatillas chunky retro",
        "descripcion": "Zapatillas con suela chunky estilo retro.",
        "precio": 27999.00,
        "stock": 12,
        "categoria": "Zapatillas",
        "marca": "StepUp",
        "imagen_url": "/static/imagenes/mock/zapatillas_chunky.webp",
    },
    {
        "id": 14,
        "nombre": "Zapatillas skate",
        "descripcion": "Zapatillas bajas con suela vulcanizada.",
        "precio": 23999.00,
        "stock": 18,
        "categoria": "Zapatillas",
        "marca": "StepUp",
        "imagen_url": "/static/imagenes/mock/zapatillas_skate.webp",
    },
    {
        "id": 15,
        "nombre": "Zapatillas trekking",
        "descripcion": "Zapatillas resistentes para senderismo.",
        "precio": 31999.00,
        "stock": 10,
        "categoria": "Zapatillas",
        "marca": "NorthWind",
        "imagen_url": "/static/imagenes/mock/zapatillas_trekking.webp",
    },

    # --- ABRIGOS ---
    {
        "id": 16,
        "nombre": "Buzo canguro friza",
        "descripcion": "Buzo con capucha, bolsillo canguro.",
        "precio": 12999.00,
        "stock": 25,
        "categoria": "Abrigos",
        "marca": "UrbanFit",
        "imagen_url": "/static/imagenes/mock/buzo_canguro.webp",
    },
    {
        "id": 17,
        "nombre": "Campera rompeviento",
        "descripcion": "Campera rompeviento impermeable.",
        "precio": 18999.00,
        "stock": 18,
        "categoria": "Abrigos",
        "marca": "NorthWind",
        "imagen_url": "/static/imagenes/mock/campera_rompeviento.webp",
    },
    {
        "id": 18,
        "nombre": "Campera puffer",
        "descripcion": "Campera acolchada tipo puffer.",
        "precio": 25999.00,
        "stock": 12,
        "categoria": "Abrigos",
        "marca": "NorthWind",
        "imagen_url": "/static/imagenes/mock/campera_puffer.webp",
    },
    {
        "id": 19,
        "nombre": "Saco de paño",
        "descripcion": "Saco de paño clásico.",
        "precio": 27999.00,
        "stock": 8,
        "categoria": "Abrigos",
        "marca": "ClassicLine",
        "imagen_url": "/static/imagenes/mock/saco_pano.webp",
    },
    {
        "id": 20,
        "nombre": "Chaleco inflable",
        "descripcion": "Chaleco liviano inflable sin mangas.",
        "precio": 16999.00,
        "stock": 20,
        "categoria": "Abrigos",
        "marca": "UrbanFit",
        "imagen_url": "/static/imagenes/mock/chaleco_inflable.webp",
    },

    # --- ACCESORIOS ---
    {
        "id": 21,
        "nombre": "Gorra trucker",
        "descripcion": "Gorra tipo trucker con red.",
        "precio": 5999.00,
        "stock": 50,
        "categoria": "Accesorios",
        "marca": "UrbanFit",
        "imagen_url": "/static/imagenes/mock/gorra_trucker.webp",
    },
    {
        "id": 22,
        "nombre": "Mochila urbana",
        "descripcion": "Mochila urbana con compartimento para notebook.",
        "precio": 18999.00,
        "stock": 30,
        "categoria": "Accesorios",
        "marca": "HomePlus",
        "imagen_url": "/static/imagenes/mock/mochila_urbana.webp",
    },
    {
        "id": 23,
        "nombre": "Cinturón de cuero sintético",
        "descripcion": "Cinturón clásico regulable.",
        "precio": 7999.00,
        "stock": 40,
        "categoria": "Accesorios",
        "marca": "ClassicLine",
        "imagen_url": "/static/imagenes/mock/cinturon_cuero.webp",
    },
    {
        "id": 24,
        "nombre": "Medias deportivas x3",
        "descripcion": "Pack de 3 pares de medias deportivas.",
        "precio": 4999.00,
        "stock": 60,
        "categoria": "Accesorios",
        "marca": "ProSport",
        "imagen_url": "/static/imagenes/mock/medias_deportivas.webp",
    },
    {
        "id": 25,
        "nombre": "Riñonera street",
        "descripcion": "Riñonera de tela resistente, varios bolsillos.",
        "precio": 8999.00,
        "stock": 25,
        "categoria": "Accesorios",
        "marca": "UrbanFit",
        "imagen_url": "/static/imagenes/mock/rinonera_street.webp",
    },

    # --- HOGAR / OFICINA ---
    {
        "id": 26,
        "nombre": "Almohadón decorativo",
        "descripcion": "Almohadón estampado para sillón.",
        "precio": 6999.00,
        "stock": 30,
        "categoria": "Hogar",
        "marca": "HomePlus",
        "imagen_url": "/static/imagenes/mock/almohadon_decorativo.webp",
    },
    {
        "id": 27,
        "nombre": "Manta polar",
        "descripcion": "Manta polar suave, tamaño 1,5 plazas.",
        "precio": 8999.00,
        "stock": 20,
        "categoria": "Hogar",
        "marca": "HomePlus",
        "imagen_url": "/static/imagenes/mock/manta_polar.webp",
    },
    {
        "id": 28,
        "nombre": "Taza de cerámica",
        "descripcion": "Taza de cerámica 300 ml.",
        "precio": 3499.00,
        "stock": 40,
        "categoria": "Hogar",
        "marca": "HomePlus",
        "imagen_url": "/static/imagenes/mock/taza_ceramica.webp",
    },
    {
        "id": 29,
        "nombre": "Lámpara de escritorio LED",
        "descripcion": "Lámpara con brazo articulado y luz regulable.",
        "precio": 12999.00,
        "stock": 15,
        "categoria": "Oficina",
        "marca": "OfficePro",
        "imagen_url": "/static/imagenes/mock/lampara_escritorio.webp",
    },
    {
        "id": 30,
        "nombre": "Silla ergonómica gamer",
        "descripcion": "Silla ergonómica con apoyabrazos regulables.",
        "precio": 59999.00,
        "stock": 8,
        "categoria": "Oficina",
        "marca": "OfficePro",
        "imagen_url": "/static/imagenes/mock/silla_ergonomica.webp",
    },
    {
    "id": 31,
    "nombre": "Buzo polar térmico",
    "descripcion": "Buzo térmico liviano ideal para días fríos.",
    "precio": 15999.0,
    "stock": 20,
    "categoria": "Abrigos",
    "marca": "NorthWind",
    "imagen": "/static/imagenes/mock/buzo_polar_termico.webp"
},
{
    "id": 32,
    "nombre": "Campera softshell outdoor",
    "descripcion": "Campera resistente al viento con interior micropolar.",
    "precio": 22999.0,
    "stock": 15,
    "categoria": "Abrigos",
    "marca": "NorthWind",
    "imagen": "/static/imagenes/mock/campera_softshell.webp"
},
{
    "id": 33,
    "nombre": "Sweater tejido unisex",
    "descripcion": "Sweater clásico tejido a máquina.",
    "precio": 17999.0,
    "stock": 18,
    "categoria": "Abrigos",
    "marca": "ClassicLine",
    "imagen": "/static/imagenes/mock/sweater_unisex.webp"
},
{
    "id": 34,
    "nombre": "Remera cuello en V",
    "descripcion": "Remera básica cuello en V, algodón suave.",
    "precio": 6299.99,
    "stock": 42,
    "categoria": "Remeras",
    "marca": "UrbanFit",
    "imagen": "/static/imagenes/mock/remera_v.webp"
},
{
    "id": 35,
    "nombre": "Remera tie-dye pastel",
    "descripcion": "Remera estampada con patrón tie-dye.",
    "precio": 7999.99,
    "stock": 30,
    "categoria": "Remeras",
    "marca": "UrbanFit",
    "imagen": "/static/imagenes/mock/remera_tiedye.webp"
},
{
    "id": 36,
    "nombre": "Remera oversize beige",
    "descripcion": "Remera oversize unisex.",
    "precio": 6999.0,
    "stock": 25,
    "categoria": "Remeras",
    "marca": "UrbanFit",
    "imagen": "/static/imagenes/mock/remera_oversize_beige.webp"
},
{
    "id": 37,
    "nombre": "Pantalón jogger cargo",
    "descripcion": "Jogger con bolsillos cargo y puños ajustados.",
    "precio": 13999.0,
    "stock": 28,
    "categoria": "Pantalones",
    "marca": "ProSport",
    "imagen": "/static/imagenes/mock/jogger_cargo.webp"
},
{
    "id": 38,
    "nombre": "Jean recto gris",
    "descripcion": "Jean corte recto lavado gris.",
    "precio": 14999.0,
    "stock": 23,
    "categoria": "Pantalones",
    "marca": "DenimCo",
    "imagen": "/static/imagenes/mock/jean_recto_gris.webp"
},
{
    "id": 39,
    "nombre": "Short deportivo training",
    "descripcion": "Short respirable ideal para entrenamientos.",
    "precio": 8999.0,
    "stock": 35,
    "categoria": "Pantalones",
    "marca": "ProSport",
    "imagen": "/static/imagenes/mock/short_training.webp"
},
{
    "id": 40,
    "nombre": "Pantalón gabardina verde",
    "descripcion": "Chino de gabardina verde oliva.",
    "precio": 13999.0,
    "stock": 18,
    "categoria": "Pantalones",
    "marca": "ClassicLine",
    "imagen": "/static/imagenes/mock/chino_verde.webp"
},
{
    "id": 41,
    "nombre": "Zapatillas urbanas negras",
    "descripcion": "Zapatillas urbanas con suela antideslizante.",
    "precio": 26999.0,
    "stock": 20,
    "categoria": "Zapatillas",
    "marca": "StepUp",
    "imagen": "/static/imagenes/mock/zapatillas_urbanas_negras.webp"
},
{
    "id": 42,
    "nombre": "Zapatillas running livianas",
    "descripcion": "Zapatillas ultralivianas para correr.",
    "precio": 28999.0,
    "stock": 18,
    "categoria": "Zapatillas",
    "marca": "ProSport",
    "imagen": "/static/imagenes/mock/zapatillas_running_livianas.webp"
},
{
    "id": 43,
    "nombre": "Zapatillas retro color pastel",
    "descripcion": "Modelo retro con colores suaves.",
    "precio": 27999.0,
    "stock": 12,
    "categoria": "Zapatillas",
    "marca": "StepUp",
    "imagen": "/static/imagenes/mock/zapatillas_retro_pastel.webp"
},
{
    "id": 44,
    "nombre": "Zapatillas outdoor impermeables",
    "descripcion": "Zapatillas para trekking con membrana waterproof.",
    "precio": 33999.0,
    "stock": 10,
    "categoria": "Zapatillas",
    "marca": "NorthWind",
    "imagen": "/static/imagenes/mock/zapatillas_waterproof.webp"
},
{
    "id": 45,
    "nombre": "Gorra deportiva clásica",
    "descripcion": "Gorra liviana con ajuste trasero.",
    "precio": 4999.0,
    "stock": 50,
    "categoria": "Accesorios",
    "marca": "UrbanFit",
    "imagen": "/static/imagenes/mock/gorra_deportiva.webp"
},
{
    "id": 46,
    "nombre": "Medias deportivas pack x3",
    "descripcion": "Medias de algodón respirable.",
    "precio": 3999.0,
    "stock": 60,
    "categoria": "Accesorios",
    "marca": "ProSport",
    "imagen": "/static/imagenes/mock/medias_pack.webp"
},
{
    "id": 47,
    "nombre": "Cinturón cuero sintético",
    "descripcion": "Cinturón resistente con hebilla metálica.",
    "precio": 7999.0,
    "stock": 34,
    "categoria": "Accesorios",
    "marca": "ClassicLine",
    "imagen": "/static/imagenes/mock/cinturon_cuero.webp"
},
{
    "id": 48,
    "nombre": "Gafas deportivas UV400",
    "descripcion": "Gafas para entrenamiento al aire libre.",
    "precio": 14999.0,
    "stock": 22,
    "categoria": "Accesorios",
    "marca": "ProSport",
    "imagen": "/static/imagenes/mock/gafas_deportivas.webp"
},
{
    "id": 49,
    "nombre": "Campera bomber negra",
    "descripcion": "Bomber clásica, liviana y versátil.",
    "precio": 21999.0,
    "stock": 20,
    "categoria": "Abrigos",
    "marca": "UrbanFit",
    "imagen": "/static/imagenes/mock/campera_bomber.webp"
},
{
    "id": 50,
    "nombre": "Campera denim forrada",
    "descripcion": "Campera de jean con interior de corderito.",
    "precio": 25999.0,
    "stock": 15,
    "categoria": "Abrigos",
    "marca": "DenimCo",
    "imagen": "/static/imagenes/mock/campera_denim_corderito.webp"
},
{
    "id": 51,
    "nombre": "Remera dry-fit gris",
    "descripcion": "Remera técnica para entrenamiento intenso.",
    "precio": 7999.0,
    "stock": 30,
    "categoria": "Remeras",
    "marca": "ProSport",
    "imagen": "/static/imagenes/mock/remera_dryfit_gris.webp"
},
{
    "id": 52,
    "nombre": "Remera estampada pixel art",
    "descripcion": "Remera con estampa estilo pixeleado.",
    "precio": 6999.0,
    "stock": 20,
    "categoria": "Remeras",
    "marca": "UrbanFit",
    "imagen": "/static/imagenes/mock/remera_pixelart.webp"
},
{
    "id": 53,
    "nombre": "Short playa flores",
    "descripcion": "Short liviano estampado floral.",
    "precio": 10999.0,
    "stock": 25,
    "categoria": "Pantalones",
    "marca": "UrbanFit",
    "imagen": "/static/imagenes/mock/short_flores.webp"
},
{
    "id": 54,
    "nombre": "Jean ancho relaxed",
    "descripcion": "Jean estilo relaxed fit.",
    "precio": 16999.0,
    "stock": 18,
    "categoria": "Pantalones",
    "marca": "DenimCo",
    "imagen": "/static/imagenes/mock/jean_relaxed.webp"
},
{
    "id": 55,
    "nombre": "Zapatillas urbanas minimalistas",
    "descripcion": "Diseño minimalista en cuero sintético.",
    "precio": 24999.0,
    "stock": 14,
    "categoria": "Zapatillas",
    "marca": "StepUp",
    "imagen": "/static/imagenes/mock/zapatillas_minimalistas.webp"
},
{
    "id": 56,
    "nombre": "Zapatillas running espuma reactiva",
    "descripcion": "Amortiguación superior con espuma reactiva.",
    "precio": 31999.0,
    "stock": 16,
    "categoria": "Zapatillas",
    "marca": "ProSport",
    "imagen": "/static/imagenes/mock/zapatillas_espuma.webp"
},

]